-- Create footer_settings table
CREATE TABLE IF NOT EXISTS public.footer_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT DEFAULT 'Juicetry - جوستري',
    company_description TEXT DEFAULT 'أفضل العصائر الطبيعية الطازجة',
    company_logo TEXT,
    phone TEXT DEFAULT '+966 50 123 4567',
    email TEXT DEFAULT 'info@juicetry.com',
    address TEXT DEFAULT 'الرياض، المملكة العربية السعودية',
    working_hours TEXT DEFAULT 'يومياً من 8 صباحاً - 11 مساءً',
    facebook_url TEXT,
    instagram_url TEXT,
    twitter_url TEXT,
    youtube_url TEXT,
    whatsapp_number TEXT,
    show_quick_links BOOLEAN DEFAULT true,
    quick_link_1_text TEXT DEFAULT 'الرئيسية',
    quick_link_1_url TEXT DEFAULT '/',
    quick_link_2_text TEXT DEFAULT 'من نحن',
    quick_link_2_url TEXT DEFAULT '/about',
    quick_link_3_text TEXT DEFAULT 'المنتجات',
    quick_link_3_url TEXT DEFAULT '/products',
    quick_link_4_text TEXT DEFAULT 'المقالات',
    quick_link_4_url TEXT DEFAULT '/blog',
    quick_link_5_text TEXT DEFAULT 'تواصل معنا',
    quick_link_5_url TEXT DEFAULT '/contact',
    bg_color TEXT DEFAULT '#1f2937',
    text_color TEXT DEFAULT '#ffffff',
    link_color TEXT DEFAULT '#22c55e',
    link_hover_color TEXT DEFAULT '#16a34a',
    copyright_text TEXT DEFAULT '© 2024 Juicetry. جميع الحقوق محفوظة',
    show_copyright BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.footer_settings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Allow public read access" ON public.footer_settings;
DROP POLICY IF EXISTS "Allow admin full access" ON public.footer_settings;

-- Policies
CREATE POLICY "Allow public read access" ON public.footer_settings FOR SELECT USING (true);
CREATE POLICY "Allow admin full access" ON public.footer_settings FOR ALL USING (auth.role() = 'authenticated');

-- Insert default row if not exists
INSERT INTO public.footer_settings (id)
SELECT 1
WHERE NOT EXISTS (SELECT 1 FROM public.footer_settings);

-- Disable RLS temporarily for local auth
ALTER TABLE public.footer_settings DISABLE ROW LEVEL SECURITY;
