-- Create contact_page_settings table
CREATE TABLE IF NOT EXISTS public.contact_page_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_title TEXT DEFAULT 'تواصل معنا',
    hero_subtitle TEXT DEFAULT 'نحن هنا للإجابة على استفساراتك',
    hero_bg_color TEXT DEFAULT '#f0fdf4',
    hero_text_color TEXT DEFAULT '#166534',
    phone_primary TEXT DEFAULT '+966501234567',
    phone_secondary TEXT,
    email_primary TEXT DEFAULT 'info@juicetry.com',
    email_secondary TEXT,
    address TEXT DEFAULT 'الرياض، المملكة العربية السعودية',
    working_hours TEXT DEFAULT 'يومياً من 8 صباحاً - 11 مساءً',
    google_maps_url TEXT DEFAULT 'https://maps.google.com',
    google_maps_embed TEXT,
    map_title TEXT DEFAULT 'موقعنا',
    show_map BOOLEAN DEFAULT true,
    form_title TEXT DEFAULT 'أرسل لنا رسالة',
    form_description TEXT,
    show_form BOOLEAN DEFAULT true,
    whatsapp_number TEXT DEFAULT '+966501234567',
    whatsapp_message TEXT DEFAULT 'مرحباً، أريد الاستفسار عن',
    info_alignment TEXT DEFAULT 'right',
    form_alignment TEXT DEFAULT 'left',
    primary_color TEXT DEFAULT '#22c55e',
    accent_color TEXT DEFAULT '#eab308',
    text_color TEXT DEFAULT '#374151',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.contact_page_settings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Allow public read access" ON public.contact_page_settings;
DROP POLICY IF EXISTS "Allow admin full access" ON public.contact_page_settings;

-- Policies
CREATE POLICY "Allow public read access" ON public.contact_page_settings FOR SELECT USING (true);
CREATE POLICY "Allow admin full access" ON public.contact_page_settings FOR ALL USING (auth.role() = 'authenticated');

-- Insert default row
INSERT INTO public.contact_page_settings (id)
SELECT 1
WHERE NOT EXISTS (SELECT 1 FROM public.contact_page_settings);
